/* Data generated by scripts/build_site.py and indexes to query it. They only change when the public version of the
   site opens the private data (session.ts): then the whole application is drawn again (App, keyed by `dataset`) */
import { createSignal } from 'solid-js';
import type { Branch, Category, Data, Doc, Person, ResearchKey } from './types';

// Values that come from the notes (frontmatter and file names): they are content, so they stay in Spanish
export const REVIEW_PENDING = 'pendiente';
export const REVIEW_DONE = 'revisada';
export const CATEGORIES: Category[] = ['genealogia', 'foto', 'arbol', 'contexto', 'patrimonio', 'ia'];
export const GENEALOGY: Category = 'genealogia';
export const PHOTO: Category = 'foto';
export const AI: Category = 'ia';
/** `status` values the documents view filters by: all but `documentado`, the usual one */
export const STATUS_FILTERS = ['indicio', 'en-investigacion', 'pendiente', 'no-fiable'];
/** `type` of the compilations: sources that group several documents */
export const COMPILATION_TYPE = 'Recopilación';
/** Research documents (`<name>.md` in the research folder, `paths.research`); the names are also the `r:` panels of the hash */
export const INCONSISTENCIES: ResearchKey = 'incoherencias';
export const PENDING: ResearchKey = 'pendientes';
export const REVISION: ResearchKey = 'revision';

export let DATA: Data;
export let P: Map<string, Person>;
export let S: Map<string, Doc>;
export let BR: Map<string, Branch>;
export let pendingDocs: Doc[];

const [dataset, setDataset] = createSignal<Data | null>(null);
/** The data being shown (null while they are replaced) */
export { dataset };

export function initData(data: Data): void {
  DATA = data;
  P = new Map(data.people.map(p => [p.id, p]));
  S = new Map(data.docs.map(d => [d.id, d]));
  BR = new Map(data.branches.map(b => [b.key, b]));
  pendingDocs = data.docs.filter(d => d.review === REVIEW_PENDING);
  setDataset(data);
}
/** Takes the application down before other data are loaded */
export const clearData = (): void => { setDataset(null); };

export const person = (id: string): Person => P.get(id)!;
export const branchOf = (p: Person): Branch => BR.get(p.branch)!;
export const color = (id: string): string => (BR.get(P.get(id)?.branch as string) || BR.get(DATA.otherBranch)!).color;
export const catLabel = (c: string): string => DATA.categories[c as keyof Data['categories']] || c;
